highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://mithun05.github.io/vitae
author: Mithun Deshpande

# edit this section with your information
# mithun05.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Mithun Deshpande's Experience
name: Mithun Deshpande
email: mdeshpa1@binghamton.edu
email_full: mailto:mdeshpa1@binghamton.edu
website: github.io/portfolio
website_full: https://mithun05.github.io/portfolio
github: mithun05
twitter: mgd2171991
tel: +607 338 8440
tel_full: tel:+6073388440
google_maps: 'https://www.google.co.uk/maps/place/222+Main+St+Apt+6,+Binghamton,+Binghamton+City+13905'
address:
  street: 222 Main Street Apt 6
  postcode: 13905
  city: Binghamton NY
  country: USA
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
